model:
  target: models.diffusion.Diffusion_TS
  params:
    seq_length: 24
    n_feat: 5
    n_embd: 128
    timesteps: 500
    loss_type: 'l1'
    beta_sch : "cosine"
    n_heads: 8
    mlp_hidden_times: 16
    n_layer_enc : 2
    n_layer_dec : 8
    use_ff : True

solver:
  base_lr: 1.0e-5
  train_epochs: 30000
  results_folder: ./check_points/sine
  
  scheduler:
    target: utils.lr_scheduler.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 3000
      min_lr: 5.0e-6
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: data.datasets.SineDataset
    params:
      n_samples: 5000
      window: 24 
      feature_dim: 5
      save_ground_truth: True
      seed: 2024
      period: train
    shuffle: True


  test_dataset:
    target: data.datasets.SineDataset
    params:
      n_samples: 1000
      window: 24  
      feature_dim: 5
      save_ground_truth: True
      seed: 2024
      period: test
    shuffle: True
  batch_size: 128
  sample_size: 256
  shuffle: True