model:
  target: test.Diffusion_TS
  params:
    seq_length: 24
    n_feat: 5
    n_embd: 128
    timesteps: 500
    loss_type: 'l1'
    beta_sch : "cosine"
    n_heads: 8
    mlp_hidden_times: 8
    n_layer_enc : 2
    n_layer_dec : 8
    use_ff : True
    use_adv : False
    loss_decomposition: False
solver:
  base_lr: 1.0e-5
  train_epochs: 20000
  results_folder: ./check_points/stock
  
  scheduler:
    target: utils.lr_scheduler.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 3000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: data.datasets.PredictionStock
    params:
      symbol : 'AAPL, MSFT, NVDA, AMZN, COST'
      sdate : '20000101'
      edate : '20131231'
      window: 24 
      save_ground_truth: True
      normalize: True
      period: train
    shuffle: True

  test_dataset:
    target: data.datasets.PredictionStock
    params:
      symbol : 'AAPL, MSFT, NVDA, AMZN, COST'
      sdate : '20140101'
      edate : '20241231'
      window: 24  
      save_ground_truth: True
      normalize: True
      period: test
    shuffle: False

  batch_size: 128
  sample_size: 256
  